### ISSUE TITLE
Error on device update! on Home Assistant 0.95.2

### ISSUE THREAD

**Issue by nschimme** [MatthewFlamm/nws#3]
Installed on Hass.io under `custom_components/nws`

Integrated in `config.yaml` as:
```
weather:
  - platform: nws
    api_key: !secret emailaddress
```

Logs show:
```
nws: Error on device update!

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 261, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 375, in async_device_update
    await self.async_update()
  File "/config/custom_components/nws/weather.py", line 187, in async_update
    self._metar_obs = self._metar(self._observation['rawMessage'])
  File "/usr/local/lib/python3.7/site-packages/metar/Metar.py", line 369, in __init__
    code = self.code+" "    # (the regexps all expect trailing spaces...)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by MatthewFlamm** [comment]
Thanks!  This looks like there is a null metar code and the `metar` package cannot handle this.

**Comment by MatthewFlamm** [comment]
Please update.  The version I just pushed here should fix it.

**Comment by nschimme** [comment]
Thanks @MatthewFlamm ! I hope support for this gets merged into mainline soon :-)
